routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/', function () {
    return view('home');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/foro', 'ForoController@forum')->name('Foro');

Route::get('/construcciones', 'ConstruccionesController@index')->name('Construcciones');

//Route::post('/construcciones', 'ConstruccionesController@store')->name('ConstruccionesStore');

Route::get('/juegos', 'JuegosController@games')->name('Juegos');

Route::get('/plataformas', 'PlataformasController@platforms')->name('Plataformas');

Route::get('/nuevaversion', 'NuevaVersionController@newversion')->name('Versión 1.17');

//Route::post('/foro', 'ForoController@store')->name('ForoStore');

Route::resource('construcciones', 'ConstruccionesController');

app/Construccion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Construccion extends Model
{
    protected $table = 'construcciones';

    protected $fillable = [
        'titulo', 'descripcion', 'imagen',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ConstruccionesController.php
<?php

namespace App\Http\Controllers;

use App\Construccion;
use auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ConstruccionesController extends Controller
{
    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('construcciones');
    }

    public function store(Request $request)
    {
       //dd($request->all());
       $request->validate([
           'imagen' => 'required|image|max:800'
       ]);

        $construccion = new Construccion;

        $request->file('imagen')->store('public');
        $imagen = $request->file('imagen')->store('public');
        $url = Storage::url($imagen);

        $construccion->user_id = Auth::user()->id;
        $construccion->titulo = $request->input('titulo');
        $construccion->descripcion = $request->input('descripcion');
        $construccion->imagen = $url;
        $construccion->save();

        return redirect('/foro');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ForoController.php
<?php

namespace App\Http\Controllers;

use App\Construccion;
use Illuminate\Http\Request;

class ForoController extends Controller
{
    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function forum()
    {
        $construcciones = \DB::table('construcciones')
                 ->select('construcciones.*')
                 ->orderBy('id', 'DESC')
                 ->get();
        return view('foro', ['builts' => $construcciones]);
    }

    public function store(Request $request)
    {
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/JuegosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class JuegosController extends Controller
{
    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function games()
    {
        return view('juegos');
    }
}

app/Http/Controllers/NuevaVersionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NuevaVersionController extends Controller
{
    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function newversion()
    {
        return view('nuevaversion');
    }
}

app/Http/Controllers/PlataformasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PlataformasController extends Controller
{
    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function platforms()
    {
        return view('plataformas');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>@yield('title')</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link rel="stylesheet" href="{{URL::asset('estilo.css')}}"> 

    </head>

    <body id="@yield('id')">

        @include('header')
        @yield('content')
        @include('footer')

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <script src="{{URL::asset('js/index.js')}}"></script>

    </body>

</html>

resources/views/construcciones.blade.php
@extends('app')

@section('title', 'Minecraft | Publicar Construcción')
@section('id', 'construcciones')

@section('content')

<br><br>
<div class="container pt-4 pb-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">Publicar Construcción</div>

                <div class="card-body">
                    <form action="{{ route('construcciones.store') }}" method="post" enctype="multipart/form-data">
                        @csrf

                            <div class="form-group row">
                              <label for="imagen" class="col-md-4 col-form-label text-md-right">Imagén</label>
                              <input type="file" class="form-control-file col-md-6" id="imagen" name="imagen" accept="image/*">
                              
                              @error('imagen')
                                <strong class="text-danger">{{$message}}</strong>
                              @enderror
                            </div>

                        <div class="form-group row">
                            <label for="titulo" class="col-md-4 col-form-label text-md-right">Titulo</label>

                            <div class="col-md-6">
                                <input id="titulo" type="text" class="form-control" name="titulo" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right">Descripción</label>

                            <div class="col-md-6">
                                <textarea id="descripcion" type="text" class="form-control" name="descripcion" required autofocus></textarea>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">Publicar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>

@endsection

resources/views/footer.blade.php
<!-- FOOTER -->

<footer>

    <div id="footer" class="pt-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-12 text-center">
                    <p>Copyright 2021 Minecraft</p>
                </div>
            </div>
        </div>
    </div>

</footer>

<!-- END FOOTER -->

resources/views/foro.blade.php
@extends('app')

@section('title', 'Minecraft | Foro')
@section('id', 'foro')

@section('content')

<!-- CONTENIDO -->
<section>
  <div class="container pt-2">
      <div class="row">
          <div class="col text-right">
            <a href="{{ route('construcciones.index') }}" class="btn btn-secondary">Publicar Construcción</a>
          </div>
      </div>
  </div>
</section>

<section class="pb-4 pt-4">
    <div class="container pt-4 pb-4" id="contenido">
        <div class="row">

            @foreach ($builts as $built)
            <div class="col-12 col-lg-6 col-md-6 col-sm-12 pb-4">
              <div class="card d-block mx-auto" style="width: 18rem;">
                  <img src="{{ $built->imagen }}" class="card-img-top" id="tarjeta">
                  <div class="card-body">
                    <h5 class="card-title">{{ $built->titulo }}</h5>
                    <p class="card-text">{{ $built->descripcion }}</p>
                  </div>
                </div>
            </div>
            @endforeach

        </div>
    </div>
</section>

<!-- END CONTENIDO -->

@endsection

resources/views/header.blade.php
<!-- HEADER -->

<header>
    <nav class="header navbar navbar-expand-lg navbar-dark fixed-top" id="cabecera">
        <div class="container">
        <a class="navbar-brand" href="{{URL::asset('/')}}">Minecraft</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
  
            <li class="nav-item">
              <a class="nav-link" href="{{URL::asset('/login')}}">Foro</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{{URL::asset('/juegos')}}">Juegos</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{{URL::asset('/plataformas')}}">Plataformas</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{{URL::asset('/nuevaversion')}}">Versión 1.17</a>
            </li>
  
          </ul>
        </div>
         </div>
      </nav>
  </header>
  
  <!-- END HEADER -->

resources/views/home.blade.php
@extends('app')

@section('title', 'Minecraft')
@section('id', 'principal')

@section('content')

<!-- CONTENIDO -->

<section class="pb-4 pt-4">
    <div class="container pt-4" id="contenido">
        <div class="row">
            <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                <p>Minecraft es un videojuego de construcción, de tipo mundo abierto o sandbox creado
                    originalmente por el sueco Markus Persson (conocido comúnmente como "Notch"),​ y posteriormente
                    desarrollado por su empresa, Mojang Studios. Fue lanzado públicamente el 17 de mayo de 2009, 
                    después de diversos cambios fue lanzada su versión completa el 18 de noviembre de 2011.
                </p>
            </div>
        </div>
    </div>

    <div class="container" id="galeria">
        <div class="row">
            <div class="col-12 col-lg-12 col-md-12 align-items-center">
                <img class="img-fluid rounded mx-auto d-block" src="images/image1.jpg">
            </div>
        </div>
    </div>

    <div class="container pt-4 pb-2" id="contenido">
        <div class="row">
            <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                <p>El 15 de septiembre de 2014, fue adquirido por la empresa Microsoft por un valor de 2500
                   millones USD. Este suceso provocó el alejamiento de Markus Persson de la compañía.
                </p>
            </div>
        </div>
    </div>

</section>

<section class="pt-4 pb-4">
    <div class="container ">
        <div class="row">
            <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card" style="width: 18rem;" id="tarjeta">
                    <img src="images/notch.jpg" class="card-img-top">
                    <div class="card-body">
                      <p class="card-text">Markus Alexej Persson (Notch) creador y programador de Minecraft y 
                          fundador de Mojang.</p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</section>

<!-- END CONTENIDO -->

@endsection

resources/views/juegos.blade.php
@extends('app')

@section('title', 'Minecraft | Juegos')
@section('id', 'juegos')

@section('content')
    
    <!-- CONTENIDO -->
<section class="pb-4">
    <div class="container">
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="images/image1.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel1.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft</h5>
                          <p>Diferentes biomas</p>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel2.png" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft</h5>
                          <p>Cuevas para explorar</p>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container pt-4" id="contenido">
            <div class="row">
                <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                    <p>Minecraft es un juego de mundo abierto, por lo que no posee un objetivo específico, 
                        permitiéndole al jugador una gran libertad en cuanto a la elección de su forma de jugar.
                        A pesar de ello, el juego posee un sistema de logros.​ El modo de juego predeterminado 
                        es en primera persona, aunque los jugadores tienen la posibilidad de cambiarlo a tercera 
                        persona.​ El juego se centra en la colocación y destrucción de bloques, siendo que este se 
                        compone de objetos tridimensionales cúbicos, colocados sobre un patrón de rejilla fija.
                        Estos cubos o bloques representan principalmente distintos elementos de la naturaleza, 
                        como tierra, piedra, minerales, troncos, entre otros. Los jugadores son libres de 
                        desplazarse por su entorno y modificarlo mediante la creación, recolección y transporte
                        de los bloques que componen al juego, los cuales solo pueden ser colocados respetando la 
                        rejilla fija del juego. ​Los jugadores crean granjas que son para conseguir un determinado
                        material más fácil por ejemplo una granja de oro. En el juego se pueden encontrar 
                        estructuras especiales como aldeas, galerías mineras, templos marinos, pirámides y 
                        templos selváticos.
                    </p>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="pb-4">
    <div class="container">
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="images/dungeons.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Dungeons</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel3.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Dungeons</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel4.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Dungeons</h5>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container pt-4" id="contenido">
            <div class="row">
                <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                    <p>A diferencia de Minecraft, Minecraft Dungeons no tiene artesanía, construcción o la 
                        capacidad de destruir bloques. En cambio, se centra en ser un juego de rastreo de mazmorras,
                        donde el jugador explora mazmorras generadas aleatoriamente llenas de monstruos generados
                        aleatoriamente, trata con trampas y rompecabezas, y encuentra tesoros aleatorios.​ 
                        No hay un sistema de clases. Un jugador puede usar cualquier arma o armadura que desee.
                    </p>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="pb-4">
    <div class="container">
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="images/educationedition.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Education Edition</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel5.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Education Edition</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel6.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Education Edition</h5>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container pt-4" id="contenido">
            <div class="row">
                <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                    <p>Minecraft Education Edition es una versión educativa del juego base, diseñada específicamente
                         para su uso en establecimientos educativos como escuelas, y construida a partir del código
                          base de Bedrock. Está disponible en Windows 10, MacOS, iPadOS y Chrome OS. Incluye un paquete
                           de recursos de química, planes de lecciones gratuitos en el sitio web de Minecraft: 
                           Education Edition y dos aplicaciones complementarias gratuitas: Code Connection y Classroom
                            Mode. <br>
 
                        Se llevó a cabo una prueba beta inicial entre el 9 de junio y el 1 de noviembre de 2016. 
                        El juego completo se lanzó en Windows 10 y MacOS el 1 de noviembre de 2016. El 20 de agosto 
                        de 2018, Mojang Studios anunció que llevaría Education Edition a iPadOS en otoño de 2018. Se 
                        lanzó a la App Store el 6 de septiembre de 2018. El 27 de marzo de 2019, se anunció que JD.com
                         administraría la Edición Educativa en China. El 26 de junio de 2020, se puso a disposición una 
                         versión beta pública de Education Edition para los Chromebooks compatibles con Google Play Store. El juego completo se lanzó en Google Play Store para Chromebooks el 7 de agosto de 2020.
                    </p>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="pb-4">
    <div class="container">
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="images/earth.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Earth</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel7.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Earth</h5>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="images/carrusel8.jpg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5>Minecraft Earth</h5>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container pt-4" id="contenido">
            <div class="row">
                <div class="col-12 col-lg-12 col-md-12 col-sm-12">
                    <p>Minecraft Education Edition es una versión educativa del juego base, diseñada específicamente
                         para su uso en establecimientos educativos como escuelas, y construida a partir del código
                          base de Bedrock. Está disponible en Windows 10, MacOS, iPadOS y Chrome OS. Incluye un paquete
                           de recursos de química, planes de lecciones gratuitos en el sitio web de Minecraft: 
                           Education Edition y dos aplicaciones complementarias gratuitas: Code Connection y Classroom
                            Mode. <br>
 
                        Se llevó a cabo una prueba beta inicial entre el 9 de junio y el 1 de noviembre de 2016. 
                        El juego completo se lanzó en Windows 10 y MacOS el 1 de noviembre de 2016. El 20 de agosto 
                        de 2018, Mojang Studios anunció que llevaría Education Edition a iPadOS en otoño de 2018. Se 
                        lanzó a la App Store el 6 de septiembre de 2018. El 27 de marzo de 2019, se anunció que JD.com
                         administraría la Edición Educativa en China. El 26 de junio de 2020, se puso a disposición una 
                         versión beta pública de Education Edition para los Chromebooks compatibles con Google Play Store. El juego completo se lanzó en Google Play Store para Chromebooks el 7 de agosto de 2020.
                    </p>
                </div>
            </div>
        </div>
    </div>

</section>

<!-- END CONTENIDO -->

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>